## Database Structure \(SQLite\) 

The 5th file, “HotelWithTestJoinNormalisation\.db,” is the complete and final database version, as it includes the test data, joins, and normalisation\.

Tables with foreign keys \(master data\)

Note: The SQL code corresponds to the schema used in the submitted database file \(SQLite\)\. Errors may occur when running the code in Deepnote, as SQLite\-specific commands such as AUTOINCREMENT are not supported\. For the submission, the original database code was included unchanged to ensure it matches the data model\.

In [ ]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_26 = _dntk.execute_sql(
  'CREATE TABLE address (\n  address_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  street        VARCHAR(100) NOT NULL,\n  house_number  VARCHAR(10)  NOT NULL,\n  zip_code      VARCHAR(10)  NOT NULL,\n  city          VARCHAR(50)  NOT NULL,\n  country       VARCHAR(50)  NOT NULL\n);\n\nCREATE TABLE booking_status (\n  booking_status_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  name                 VARCHAR(50) NOT NULL\n);\n\nCREATE TABLE hotel_facility (\n  hotel_facility_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  icon                 VARCHAR(100) NOT NULL,\n  name                 VARCHAR(50)  NOT NULL,\n  description          VARCHAR(100)\n);\n\nCREATE TABLE room_facility (\n  room_facility_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  icon                VARCHAR(100) NOT NULL,\n  name                VARCHAR(50)  NOT NULL,\n  description         VARCHAR(100)\n);\n\nCREATE TABLE season_code (\n  season_code_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  name              VARCHAR(50) NOT NULL,\n  valid_from        DATE        NOT NULL,\n  valid_to          DATE        NOT NULL\n);\n\nCREATE TABLE type_code (\n  type_code_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  name            VARCHAR(50) NOT NULL\n);\n\nCREATE TABLE payment_method (\n  payment_method_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  name                 VARCHAR(50) NOT NULL\n);\n\nCREATE TABLE service_type (\n  service_type_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  name               VARCHAR(100) NOT NULL\n);\n\nCREATE TABLE owner (\n  owner_id_PK         INTEGER PRIMARY KEY AUTOINCREMENT,\n  owner_address_id_FK INTEGER(10) NOT NULL,\n  first_name          VARCHAR(50) NOT NULL,\n  last_name           VARCHAR(50) NOT NULL,\n\n  FOREIGN KEY (owner_address_id_FK)\n    REFERENCES address (address_id_PK)\n);\n\nCREATE TABLE guest (\n  guest_id_PK         INTEGER PRIMARY KEY AUTOINCREMENT,\n  guest_address_id_FK INTEGER(10) NOT NULL,\n  first_name          VARCHAR(50) NOT NULL,\n  last_name           VARCHAR(50) NOT NULL,\n  phone_number        VARCHAR(20) NOT NULL,\n  email_address       VARCHAR(70) NOT NULL UNIQUE,\n  passport_number     VARCHAR(50) NOT NULL UNIQUE,\n\n  FOREIGN KEY (guest_address_id_FK)\n    REFERENCES address (address_id_PK)\n);\n\nCREATE TABLE hotel (\n  hotel_id_PK           INTEGER PRIMARY KEY AUTOINCREMENT,\n  owner_id_FK           INTEGER(10) NOT NULL,\n  hotel_address_id_FK   INTEGER(10) NOT NULL,\n  name                  VARCHAR(50) NOT NULL,\n  stars                 INTEGER(1)  NOT NULL,\n  pets_allowed          BOOLEAN     NOT NULL,\n  wheelchair_accessible BOOLEAN     NOT NULL,\n\n  FOREIGN KEY (owner_id_FK)\n    REFERENCES owner (owner_id_PK),\n\n  FOREIGN KEY (hotel_address_id_FK)\n    REFERENCES address (address_id_PK)\n);\n\nCREATE TABLE room_type (\n  room_type_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  type_code_id_FK INTEGER(10) NOT NULL,\n  description     VARCHAR(100) NOT NULL,\n\n  FOREIGN KEY (type_code_id_FK)\n    REFERENCES type_code (type_code_id_PK)\n);\n\nCREATE TABLE room (\n  room_id_PK      INTEGER PRIMARY KEY AUTOINCREMENT,\n  hotel_id_FK     INTEGER(10) NOT NULL,\n  room_type_id_FK INTEGER(10) NOT NULL,\n  room_number     VARCHAR(10) NOT NULL,\n  max_guests      INTEGER(10) NOT NULL,\n\n  FOREIGN KEY (hotel_id_FK)\n    REFERENCES hotel (hotel_id_PK),\n\n  FOREIGN KEY (room_type_id_FK)\n    REFERENCES room_type (room_type_id_PK),\n\n  UNIQUE (hotel_id_FK, room_number)\n);\n\nCREATE TABLE room_price (\n  room_price_id_PK  INTEGER PRIMARY KEY AUTOINCREMENT,\n  season_code_id_FK INTEGER(10)    NOT NULL,\n  room_type_id_FK   INTEGER(10)    NOT NULL,\n  price_per_night   DECIMAL(10, 2) NOT NULL,\n\n  FOREIGN KEY (season_code_id_FK)\n    REFERENCES season_code (season_code_id_PK),\n\n  FOREIGN KEY (room_type_id_FK)\n    REFERENCES room_type (room_type_id_PK),\n\n  UNIQUE (season_code_id_FK, room_type_id_FK)\n);\n\nCREATE TABLE hotel_has_facility (\n  hotel_has_facility_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  hotel_id_FK              INTEGER(10) NOT NULL,\n  hotel_facility_id_FK     INTEGER(10) NOT NULL,\n\n  FOREIGN KEY (hotel_id_FK)\n    REFERENCES hotel (hotel_id_PK),\n\n  FOREIGN KEY (hotel_facility_id_FK)\n    REFERENCES hotel_facility (hotel_facility_id_PK),\n\n  UNIQUE (hotel_id_FK, hotel_facility_id_FK)\n);\n\nCREATE TABLE room_has_facility (\n  room_has_facility_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  room_id_FK              INTEGER(10) NOT NULL,\n  room_facility_id_FK     INTEGER(10) NOT NULL,\n\n  FOREIGN KEY (room_id_FK)\n    REFERENCES room (room_id_PK),\n\n  FOREIGN KEY (room_facility_id_FK)\n    REFERENCES room_facility (room_facility_id_PK),\n\n  UNIQUE (room_id_FK, room_facility_id_FK)\n);\n\nCREATE TABLE booking (\n  booking_id_PK        INTEGER PRIMARY KEY AUTOINCREMENT,\n  guest_id_FK          INTEGER(10)    NOT NULL,\n  booking_status_id_FK INTEGER(10)    NOT NULL,\n  room_id_FK           INTEGER(10)    NOT NULL,\n  start_date           DATE           NOT NULL,\n  end_date             DATE           NOT NULL,\n  booking_date         DATE           NOT NULL,\n  adults_number        INTEGER(10)    NOT NULL,\n  children_number      INTEGER(10),\n  with_pets            BOOLEAN        NOT NULL,\n  booking_price        DECIMAL(10, 2) NOT NULL,\n\n  FOREIGN KEY (guest_id_FK)\n    REFERENCES guest (guest_id_PK),\n\n  FOREIGN KEY (booking_status_id_FK)\n    REFERENCES booking_status (booking_status_id_PK),\n\n  FOREIGN KEY (room_id_FK)\n    REFERENCES room (room_id_PK)\n);\n\nCREATE TABLE invoice (\n  invoice_id_PK        INTEGER PRIMARY KEY AUTOINCREMENT,\n  booking_id_FK        INTEGER(10)    NOT NULL,\n  payment_method_id_FK INTEGER(10)    NOT NULL,\n  invoice_date         DATE           NOT NULL,\n  currency             VARCHAR(3)     NOT NULL,\n  paid_date            DATE,\n  total_price          DECIMAL(10, 2) NOT NULL,\n\n  FOREIGN KEY (booking_id_FK)\n    REFERENCES booking (booking_id_PK),\n\n  FOREIGN KEY (payment_method_id_FK)\n    REFERENCES payment_method (payment_method_id_PK)\n);\n\nCREATE TABLE invoice_item (\n  invoice_item_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n  invoice_id_FK      INTEGER(10)    NOT NULL,\n  service_type_id_FK INTEGER(10)    NOT NULL,\n  description        VARCHAR(255)   NOT NULL,\n  quantity           INTEGER(10)    NOT NULL,\n  unit_price         DECIMAL(10, 2) NOT NULL,\n\n  FOREIGN KEY (invoice_id_FK)\n    REFERENCES invoice (invoice_id_PK),\n\n  FOREIGN KEY (service_type_id_FK)\n    REFERENCES service_type (service_type_id_PK)\n);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_26

## Tables with test date

In [ ]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_30 = _dntk.execute_sql(
  'PRAGMA foreign_keys = ON;\n\n-- ============================================================\n-- ADDRESS\n-- ============================================================\n\nINSERT INTO address (street, house_number, zip_code, city, country) VALUES\n(\'Promenade\', \'101\', \'7270\', \'Davos Platz\', \'Switzerland\'),\n(\'Via Serlas\', \'9\', \'7500\', \'St. Moritz\', \'Switzerland\'),\n(\'Wispilenstrasse\', \'3\', \'3780\', \'Gstaad\', \'Switzerland\'),\n(\'Höheweg\', \'41\', \'3800\', \'Interlaken\', \'Switzerland\'),\n(\'Bahnhofstrasse\', \'12\', \'8001\', \'Zurich\', \'Switzerland\'),\n(\'Dorfstrasse\', \'8\', \'7260\', \'Davos\', \'Switzerland\'),\n(\'Via Maistra\', \'22\', \'7500\', \'St. Moritz\', \'Switzerland\'),\n(\'Poststrasse\', \'5\', \'3780\', \'Gstaad\', \'Switzerland\'),\n(\'Marktgasse\', \'14\', \'3011\', \'Bern\', \'Switzerland\'),\n(\'Rue du Rhône\', \'77\', \'1204\', \'Geneva\', \'Switzerland\'),\n(\'Seehofstrasse\', \'18\', \'8008\', \'Zurich\', \'Switzerland\'),\n(\'Pilatusstrasse\', \'29\', \'6003\', \'Lucerne\', \'Switzerland\'),\n(\'Alpenweg\', \'7\', \'7260\', \'Davos\', \'Switzerland\'),\n(\'Via Tinus\', \'4\', \'7500\', \'St. Moritz\', \'Switzerland\'),\n(\'Panoramastrasse\', \'11\', \'3780\', \'Gstaad\', \'Switzerland\'),\n(\'Bahnhofplatz\', \'2\', \'3001\', \'Bern\', \'Switzerland\'),\n(\'Uferweg\', \'6\', \'3800\', \'Interlaken\', \'Switzerland\'),\n(\'Schulhausstrasse\', \'27\', \'7270\', \'Davos Platz\', \'Switzerland\'),\n(\'Kreuzgasse\', \'16\', \'4058\', \'Basel\', \'Switzerland\'),\n(\'Mühlestrasse\', \'21\', \'9000\', \'St. Gallen\', \'Switzerland\');\n\n-- ============================================================\n-- OWNER\n--\n-- owner_address_id_FK refers to address(address_id_PK)\n-- Example: owner_address_id_FK = 9 means address number 9\n-- ============================================================\n\nINSERT INTO owner (owner_address_id_FK, first_name, last_name) VALUES\n(9, \'Lukas\', \'Meier\'),\n(10, \'Sophie\', \'Keller\'),\n(5, \'Marco\', \'Fischer\'),\n(16, \'Isabelle\', \'Morel\');\n\n-- ============================================================\n-- HOTEL\n--\n-- owner_id_FK refers to owner(owner_id_PK)\n-- hotel_address_id_FK refers to address(address_id_PK)\n--\n-- owner_id_FK:\n-- 1 = Lukas Meier\n-- 2 = Sophie Keller\n-- 3 = Marco Fischer\n-- 4 = Isabelle Morel\n-- ============================================================\n\nINSERT INTO hotel (owner_id_FK, hotel_address_id_FK, name, stars, pets_allowed, wheelchair_accessible) VALUES\n(1, 1, \'Alpine Peak Resort\', 5, 1, 1),\n(1, 2, \'Grand Snow Palace\', 5, 0, 1),\n(2, 3, \'Chalet Panorama Gstaad\', 4, 1, 0),\n(3, 4, \'Lakeview Lodge Interlaken\', 4, 1, 1),\n(4, 6, \'Davos Family Escape\', 4, 1, 1),\n(2, 7, \'Engadin Comfort Stay\', 3, 0, 1);\n\n-- ============================================================\n-- HOTEL FACILITY\n-- ============================================================\n\nINSERT INTO hotel_facility (icon, name, description) VALUES\n(\'wifi\', \'Free WiFi\', \'Wireless internet access throughout the hotel\'),\n(\'spa\', \'Spa\', \'Spa and wellness area\'),\n(\'parking\', \'Parking\', \'Parking spaces for guests\'),\n(\'ski\', \'Ski Storage\', \'Storage room for skis and winter sports equipment\'),\n(\'breakfast\', \'Breakfast\', \'Breakfast buffet available\'),\n(\'pool\', \'Indoor Pool\', \'Indoor swimming pool\'),\n(\'gym\', \'Fitness Room\', \'Fitness and exercise room\'),\n(\'shuttle\', \'Shuttle Service\', \'Transport or shuttle service\'),\n(\'pet\', \'Pet Friendly\', \'Pets are allowed\'),\n(\'accessible\', \'Wheelchair Accessible\', \'Accessible for wheelchair users\');\n\n-- ============================================================\n-- HOTEL_HAS_FACILITY\n--\n-- hotel_id_FK refers to hotel(hotel_id_PK)\n-- hotel_facility_id_FK refers to hotel_facility(hotel_facility_id_PK)\n--\n-- hotel_facility_id_FK:\n-- 1 = Free WiFi\n-- 2 = Spa\n-- 3 = Parking\n-- 4 = Ski Storage\n-- 5 = Breakfast\n-- 6 = Indoor Pool\n-- 7 = Fitness Room\n-- 8 = Shuttle Service\n-- 9 = Pet Friendly\n-- 10 = Wheelchair Accessible\n-- ============================================================\n\nINSERT INTO hotel_has_facility (hotel_id_FK, hotel_facility_id_FK) VALUES\n\n-- Hotel 1 = Alpine Peak Resort\n(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 9), (1, 10),\n\n-- Hotel 2 = Grand Snow Palace\n(2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 10),\n\n-- Hotel 3 = Chalet Panorama Gstaad\n(3, 1), (3, 3), (3, 4), (3, 5), (3, 9),\n\n-- Hotel 4 = Lakeview Lodge Interlaken\n(4, 1), (4, 3), (4, 5), (4, 7), (4, 9), (4, 10),\n\n-- Hotel 5 = Davos Family Escape\n(5, 1), (5, 3), (5, 4), (5, 5), (5, 9), (5, 10),\n\n-- Hotel 6 = Engadin Comfort Stay\n(6, 1), (6, 3), (6, 4), (6, 5), (6, 10);\n\n-- ============================================================\n-- TYPE CODE\n-- ============================================================\n\nINSERT INTO type_code (name) VALUES\n(\'Single Room\'),\n(\'Double Room\'),\n(\'Studio\'),\n(\'Family Room\'),\n(\'Suite\');\n\n-- ============================================================\n-- ROOM TYPE\n--\n-- type_code_id_FK refers to type_code(type_code_id_PK)\n--\n-- type_code_id_FK:\n-- 1 = Single Room\n-- 2 = Double Room\n-- 3 = Studio\n-- 4 = Family Room\n-- 5 = Suite\n-- ============================================================\n\nINSERT INTO room_type (type_code_id_FK, description) VALUES\n(1, \'Single room with one bed for one guest\'),\n(2, \'Double room with a double bed or twin beds\'),\n(3, \'Studio with kitchenette and living area\'),\n(4, \'Family room with several sleeping options\'),\n(5, \'Suite with separate living area and premium comfort\');\n\n-- ============================================================\n-- ROOM FACILITY\n-- ============================================================\n\nINSERT INTO room_facility (icon, name, description) VALUES\n(\'tv\', \'TV\', \'Flat-screen television\'),\n(\'balcony\', \'Balcony\', \'Private balcony\'),\n(\'minibar\', \'Minibar\', \'Small fridge with drinks\'),\n(\'kitchen\', \'Kitchenette\', \'Small kitchenette for cooking\'),\n(\'bathtub\', \'Bathtub\', \'Bathroom with bathtub\'),\n(\'shower\', \'Shower\', \'Bathroom with shower\'),\n(\'sofa\', \'Sofa Bed\', \'Extra sleeping space with sofa bed\'),\n(\'desk\', \'Desk\', \'Desk for work or study\'),\n(\'safe\', \'Safe\', \'In-room safe\'),\n(\'coffee\', \'Coffee Machine\', \'Coffee and tea machine\');\n\n-- ============================================================\n-- ROOM\n--\n-- hotel_id_FK refers to hotel(hotel_id_PK)\n-- room_type_id_FK refers to room_type(room_type_id_PK)\n--\n-- room_type_id_FK:\n-- 1 = Single Room\n-- 2 = Double Room\n-- 3 = Studio\n-- 4 = Family Room\n-- 5 = Suite\n-- ============================================================\n\nINSERT INTO room (hotel_id_FK, room_type_id_FK, room_number, max_guests) VALUES\n\n-- Hotel 1 = Alpine Peak Resort\n(1, 1, \'101\', 1),\n(1, 2, \'102\', 2),\n(1, 5, \'201\', 4),\n(1, 4, \'202\', 5),\n\n-- Hotel 2 = Grand Snow Palace\n(2, 2, \'301\', 2),\n(2, 3, \'302\', 3),\n(2, 5, \'401\', 4),\n\n-- Hotel 3 = Chalet Panorama Gstaad\n(3, 2, \'A12\', 2),\n(3, 4, \'B20\', 5),\n\n-- Hotel 4 = Lakeview Lodge Interlaken\n(4, 1, \'11\', 1),\n(4, 2, \'12\', 2),\n(4, 3, \'20\', 3),\n\n-- Hotel 5 = Davos Family Escape\n(5, 2, \'D1\', 2),\n(5, 4, \'D2\', 5),\n\n-- Hotel 6 = Engadin Comfort Stay\n(6, 1, \'5\', 1),\n(6, 2, \'6\', 2),\n(6, 3, \'7\', 3);\n\n-- ============================================================\n-- ROOM_HAS_FACILITY\n--\n-- room_id_FK refers to room(room_id_PK)\n-- room_facility_id_FK refers to room_facility(room_facility_id_PK)\n--\n-- room_facility_id_FK:\n-- 1 = TV\n-- 2 = Balcony\n-- 3 = Minibar\n-- 4 = Kitchenette\n-- 5 = Bathtub\n-- 6 = Shower\n-- 7 = Sofa Bed\n-- 8 = Desk\n-- 9 = Safe\n-- 10 = Coffee Machine\n-- ============================================================\n\nINSERT INTO room_has_facility (room_id_FK, room_facility_id_FK) VALUES\n\n-- Room 1\n(1, 1), (1, 6), (1, 8), (1, 9),\n\n-- Room 2\n(2, 1), (2, 2), (2, 6), (2, 8), (2, 9),\n\n-- Room 3\n(3, 1), (3, 2), (3, 3), (3, 5), (3, 9), (3, 10),\n\n-- Room 4\n(4, 1), (4, 2), (4, 5), (4, 7), (4, 9), (4, 10),\n\n-- Room 5\n(5, 1), (5, 2), (5, 6), (5, 8), (5, 9),\n\n-- Room 6\n(6, 1), (6, 2), (6, 4), (6, 6), (6, 9), (6, 10),\n\n-- Room 7\n(7, 1), (7, 2), (7, 3), (7, 5), (7, 9), (7, 10),\n\n-- Room 8\n(8, 1), (8, 2), (8, 6), (8, 9),\n\n-- Room 9\n(9, 1), (9, 2), (9, 6), (9, 7), (9, 9),\n\n-- Room 10\n(10, 1), (10, 6), (10, 8), (10, 9),\n\n-- Room 11\n(11, 1), (11, 2), (11, 6), (11, 8), (11, 9),\n\n-- Room 12\n(12, 1), (12, 4), (12, 6), (12, 9), (12, 10),\n\n-- Room 13\n(13, 1), (13, 2), (13, 6), (13, 9),\n\n-- Room 14\n(14, 1), (14, 2), (14, 6), (14, 7), (14, 9), (14, 10),\n\n-- Room 15\n(15, 1), (15, 6), (15, 8), (15, 9),\n\n-- Room 16\n(16, 1), (16, 2), (16, 4), (16, 6), (16, 9), (16, 10),\n\n-- Room 17\n(17, 1), (17, 4), (17, 6), (17, 9), (17, 10);\n\n-- ============================================================\n-- SEASON CODE\n-- ============================================================\n\nINSERT INTO season_code (name, valid_from, valid_to) VALUES\n(\'Winter Peak 2026\', \'2026-12-15\', \'2027-03-15\'),\n(\'Shoulder Season 2026\', \'2026-03-16\', \'2026-05-31\'),\n(\'Summer 2026\', \'2026-06-01\', \'2026-09-15\'),\n(\'Autumn 2026\', \'2026-09-16\', \'2026-12-14\');\n\n-- ============================================================\n-- ROOM PRICE\n--\n-- season_code_id_FK refers to season_code(season_code_id_PK)\n-- room_type_id_FK refers to room_type(room_type_id_PK)\n--\n-- season_code_id_FK:\n-- 1 = Winter Peak 2026\n-- 2 = Shoulder Season 2026\n-- 3 = Summer 2026\n-- 4 = Autumn 2026\n--\n-- room_type_id_FK:\n-- 1 = Single Room\n-- 2 = Double Room\n-- 3 = Studio\n-- 4 = Family Room\n-- 5 = Suite\n-- ============================================================\n\nINSERT INTO room_price (season_code_id_FK, room_type_id_FK, price_per_night) VALUES\n\n-- Winter Peak 2026\n(1, 1, 180.00),\n(1, 2, 260.00),\n(1, 3, 340.00),\n(1, 4, 420.00),\n(1, 5, 690.00),\n\n-- Shoulder Season 2026\n(2, 1, 110.00),\n(2, 2, 165.00),\n(2, 3, 220.00),\n(2, 4, 290.00),\n(2, 5, 450.00),\n\n-- Summer 2026\n(3, 1, 130.00),\n(3, 2, 190.00),\n(3, 3, 250.00),\n(3, 4, 320.00),\n(3, 5, 520.00),\n\n-- Autumn 2026\n(4, 1, 120.00),\n(4, 2, 175.00),\n(4, 3, 235.00),\n(4, 4, 300.00),\n(4, 5, 470.00);\n\n-- ============================================================\n-- BOOKING STATUS\n-- ============================================================\n\nINSERT INTO booking_status (name) VALUES\n(\'Pending\'),\n(\'Confirmed\'),\n(\'Checked-in\'),\n(\'Completed\'),\n(\'Cancelled\');\n\n-- ============================================================\n-- PAYMENT METHOD\n-- ============================================================\n\nINSERT INTO payment_method (name) VALUES\n(\'Cash\'),\n(\'Twint\'),\n(\'PayPal\'),\n(\'Visa\'),\n(\'Mastercard\'),\n(\'American Express\'),\n(\'Payment Slip\'),\n(\'Bank Transfer\'),\n(\'Maestro\'),\n(\'Apple Pay\');\n\n-- ============================================================\n-- SERVICE TYPE\n-- ============================================================\n\nINSERT INTO service_type (name) VALUES\n(\'Accommodation\'),\n(\'Food\'),\n(\'Service\'),\n(\'Leisure\');\n\n-- ============================================================\n-- GUEST\n--\n-- guest_address_id_FK refers to address(address_id_PK)\n-- ============================================================\n\nINSERT INTO guest (guest_address_id_FK, first_name, last_name, phone_number, email_address, passport_number) VALUES\n(11, \'Anna\', \'Schneider\', \'+41791234567\', \'anna.schneider@example.com\', \'CH7845123\'),\n(12, \'David\', \'Mueller\', \'+41795556677\', \'david.mueller@example.com\', \'DE9933112\'),\n(13, \'Elena\', \'Rossi\', \'+41794443322\', \'elena.rossi@example.com\', \'IT1200998\'),\n(14, \'Marc\', \'Dubois\', \'+41798887766\', \'marc.dubois@example.com\', \'FR8877001\'),\n(15, \'Nina\', \'Keller\', \'+41796661122\', \'nina.keller@example.com\', \'CH6655443\'),\n(17, \'Jonas\', \'Weber\', \'+41797770011\', \'jonas.weber@example.com\', \'AT9011776\'),\n(18, \'Sarah\', \'Meier\', \'+41793334455\', \'sarah.meier@example.com\', \'CH7711223\'),\n(19, \'Paul\', \'Hofmann\', \'+41795551199\', \'paul.hofmann@example.com\', \'DE5551002\'),\n(20, \'Laura\', \'Bianchi\', \'+41794449988\', \'laura.bianchi@example.com\', \'IT5522114\'),\n(8, \'Maya\', \'Singh\', \'+41798880077\', \'maya.singh@example.com\', \'IN4400881\');\n\n-- ============================================================\n-- BOOKING\n--\n-- guest_id_FK refers to guest(guest_id_PK)\n-- booking_status_id_FK refers to booking_status(booking_status_id_PK)\n-- room_id_FK refers to room(room_id_PK)\n--\n-- booking_status_id_FK:\n-- 1 = Pending\n-- 2 = Confirmed\n-- 3 = Checked-in\n-- 4 = Completed\n-- 5 = Cancelled\n-- ============================================================\n\nINSERT INTO booking (guest_id_FK, booking_status_id_FK, room_id_FK, start_date, end_date, booking_date, adults_number, children_number, with_pets, booking_price) VALUES\n\n-- Booking 1: guest 1, status 4 = Completed, room 2\n(1, 4, 2, \'2026-01-10\', \'2026-01-14\', \'2025-11-20\', 2, 0, 0, 1040.00),\n\n-- Booking 2: guest 2, status 5 = Cancelled, room 5\n(2, 5, 5, \'2026-02-05\', \'2026-02-09\', \'2025-12-18\', 2, 0, 0, 1040.00),\n\n-- Booking 3: guest 3, status 4 = Completed, room 9\n(3, 4, 9, \'2026-03-01\', \'2026-03-06\', \'2026-01-08\', 2, 2, 1, 1450.00),\n\n-- Booking 4: guest 4, status 3 = Checked-in, room 12\n(4, 3, 12, \'2026-04-20\', \'2026-04-25\', \'2026-03-02\', 2, 1, 0, 1100.00),\n\n-- Booking 5: guest 5, status 2 = Confirmed, room 15\n(5, 2, 15, \'2026-07-11\', \'2026-07-15\', \'2026-05-21\', 2, 0, 0, 760.00),\n\n-- Booking 6: guest 6, status 4 = Completed, room 7\n(6, 4, 7, \'2026-12-22\', \'2026-12-27\', \'2026-09-30\', 2, 1, 0, 3450.00),\n\n-- Booking 7: guest 7, status 2 = Confirmed, room 14\n(7, 2, 14, \'2026-08-03\', \'2026-08-08\', \'2026-06-01\', 2, 2, 1, 1600.00),\n\n-- Booking 8: guest 8, status 1 = Pending, room 10\n(8, 1, 10, \'2026-10-10\', \'2026-10-12\', \'2026-10-01\', 1, 0, 0, 240.00),\n\n-- Booking 9: guest 9, status 4 = Completed, room 3\n(9, 4, 3, \'2026-01-15\', \'2026-01-18\', \'2025-12-05\', 2, 1, 0, 2070.00),\n\n-- Booking 10: guest 10, status 2 = Confirmed, room 16\n(10, 2, 16, \'2026-05-02\', \'2026-05-05\', \'2026-04-12\', 2, 0, 0, 660.00);\n\n-- ============================================================\n-- INVOICE\n--\n-- booking_id_FK refers to booking(booking_id_PK)\n-- payment_method_id_FK refers to payment_method(payment_method_id_PK)\n--\n-- payment_method_id_FK:\n-- 1 = Cash\n-- 2 = Twint\n-- 3 = PayPal\n-- 4 = Visa\n-- 5 = Mastercard\n-- 6 = American Express\n-- 7 = Payment Slip\n-- 8 = Bank Transfer\n-- 9 = Maestro\n-- 10 = Apple Pay\n-- ============================================================\n\nINSERT INTO invoice (booking_id_FK, payment_method_id_FK, invoice_date, currency, paid_date, total_price) VALUES\n\n-- Invoice for Booking 1, payment method 4 = Visa\n(1, 4, \'2026-01-14\', \'CHF\', \'2026-01-14\', 1128.00),\n\n-- Invoice for Booking 3, payment method 2 = Twint\n(3, 2, \'2026-03-06\', \'CHF\', \'2026-03-08\', 1585.00),\n\n-- Invoice for Booking 4, payment method 7 = Payment Slip\n(4, 7, \'2026-04-25\', \'CHF\', NULL, 1175.00),\n\n-- Invoice for Booking 6, payment method 6 = American Express\n(6, 6, \'2026-12-27\', \'CHF\', \'2026-12-28\', 3695.00),\n\n-- Invoice for Booking 9, payment method 5 = Mastercard\n(9, 5, \'2026-01-18\', \'CHF\', \'2026-01-19\', 2195.00);\n\n-- ============================================================\n-- INVOICE ITEM\n--\n-- invoice_id_FK refers to invoice(invoice_id_PK)\n-- service_type_id_FK refers to service_type(service_type_id_PK)\n--\n-- service_type_id_FK:\n-- 1 = Accommodation\n-- 2 = Food\n-- 3 = Service\n-- 4 = Leisure\n-- ============================================================\n\nINSERT INTO invoice_item (invoice_id_FK, service_type_id_FK, description, quantity, unit_price) VALUES\n\n-- Invoice 1\n(1, 1, \'Double room nights\', 4, 260.00),\n(1, 2, \'Breakfast buffet\', 2, 24.00),\n(1, 3, \'Parking fee\', 2, 20.00),\n\n-- Invoice 2\n(2, 1, \'Family room nights\', 5, 290.00),\n(2, 3, \'Final cleaning\', 1, 60.00),\n(2, 4, \'Ski pass\', 1, 75.00),\n\n-- Invoice 3\n(3, 1, \'Studio nights\', 5, 220.00),\n(3, 2, \'Mini bar drinks\', 3, 15.00),\n(3, 3, \'Laundry service\', 1, 30.00),\n\n-- Invoice 4\n(4, 1, \'Suite nights\', 5, 690.00),\n(4, 2, \'Room service dinner\', 2, 45.00),\n(4, 3, \'Spa access\', 1, 155.00),\n\n-- Invoice 5\n(5, 1, \'Suite nights\', 3, 690.00),\n(5, 2, \'Breakfast buffet\', 3, 25.00),\n(5, 3, \'Parking fee\', 1, 50.00);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_30

## Tables with test and join

In [ ]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_31 = _dntk.execute_sql(
  '-- ============================================================\n-- 1) All direct JOINS\n-- ============================================================\n\n-- owner → address\nSELECT *\nFROM owner o\nJOIN address a\n    ON o.owner_address_id_FK = a.address_id_PK;\n\n-- guest → address\nSELECT *\nFROM guest g\nJOIN address a\n    ON g.guest_address_id_FK = a.address_id_PK;\n\n-- hotel → address\nSELECT *\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK;\n\n-- hotel → owner\nSELECT *\nFROM hotel h\nJOIN owner o\n    ON h.owner_id_FK = o.owner_id_PK;\n\n-- hotel → owner → owner address\nSELECT *\nFROM hotel h\nJOIN owner o\n    ON h.owner_id_FK = o.owner_id_PK\nJOIN address a\n    ON o.owner_address_id_FK = a.address_id_PK;\n\n-- hotel → hotel_has_facility\nSELECT *\nFROM hotel h\nJOIN hotel_has_facility hhf\n    ON h.hotel_id_PK = hhf.hotel_id_FK;\n\n-- hotel_has_facility → hotel_facility\nSELECT *\nFROM hotel_has_facility hhf\nJOIN hotel_facility hf\n    ON hhf.hotel_facility_id_FK = hf.hotel_facility_id_PK;\n\n-- hotel → hotel_has_facility → hotel_facility\nSELECT *\nFROM hotel h\nJOIN hotel_has_facility hhf\n    ON h.hotel_id_PK = hhf.hotel_id_FK\nJOIN hotel_facility hf\n    ON hhf.hotel_facility_id_FK = hf.hotel_facility_id_PK;\n\n-- room → hotel\nSELECT *\nFROM room r\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK;\n\n-- room → room_type\nSELECT *\nFROM room r\nJOIN room_type rt\n    ON r.room_type_id_FK = rt.room_type_id_PK;\n\n-- room_type → type_code\nSELECT *\nFROM room_type rt\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK;\n\n-- room → room_type → type_code\nSELECT *\nFROM room r\nJOIN room_type rt\n    ON r.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK;\n\n-- room → hotel → address\nSELECT *\nFROM room r\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK;\n\n-- room → room_has_facility\nSELECT *\nFROM room r\nJOIN room_has_facility rhf\n    ON r.room_id_PK = rhf.room_id_FK;\n\n-- room_has_facility → room_facility\nSELECT *\nFROM room_has_facility rhf\nJOIN room_facility rf\n    ON rhf.room_facility_id_FK = rf.room_facility_id_PK;\n\n-- room → room_has_facility → room_facility\nSELECT *\nFROM room r\nJOIN room_has_facility rhf\n    ON r.room_id_PK = rhf.room_id_FK\nJOIN room_facility rf\n    ON rhf.room_facility_id_FK = rf.room_facility_id_PK;\n\n-- room_price → room_type\nSELECT *\nFROM room_price rp\nJOIN room_type rt\n    ON rp.room_type_id_FK = rt.room_type_id_PK;\n\n-- room_price → season_code\nSELECT *\nFROM room_price rp\nJOIN season_code sc\n    ON rp.season_code_id_FK = sc.season_code_id_PK;\n\n-- room_price → room_type → type_code\nSELECT *\nFROM room_price rp\nJOIN room_type rt\n    ON rp.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK;\n\n-- room_price → season_code → room_type → type_code\nSELECT *\nFROM room_price rp\nJOIN season_code sc\n    ON rp.season_code_id_FK = sc.season_code_id_PK\nJOIN room_type rt\n    ON rp.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK;\n\n-- booking → guest\nSELECT *\nFROM booking b\nJOIN guest g\n    ON b.guest_id_FK = g.guest_id_PK;\n\n-- booking → booking_status\nSELECT *\nFROM booking b\nJOIN booking_status bs\n    ON b.booking_status_id_FK = bs.booking_status_id_PK;\n\n-- booking → room\nSELECT *\nFROM booking b\nJOIN room r\n    ON b.room_id_FK = r.room_id_PK;\n\n-- booking → guest → address\nSELECT *\nFROM booking b\nJOIN guest g\n    ON b.guest_id_FK = g.guest_id_PK\nJOIN address a\n    ON g.guest_address_id_FK = a.address_id_PK;\n\n-- booking → room → hotel\nSELECT *\nFROM booking b\nJOIN room r\n    ON b.room_id_FK = r.room_id_PK\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK;\n\n-- booking → room → room_type → type_code\nSELECT *\nFROM booking b\nJOIN room r\n    ON b.room_id_FK = r.room_id_PK\nJOIN room_type rt\n    ON r.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK;\n\n-- booking → guest → room → hotel → booking_status\nSELECT *\nFROM booking b\nJOIN guest g\n    ON b.guest_id_FK = g.guest_id_PK\nJOIN room r\n    ON b.room_id_FK = r.room_id_PK\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nJOIN booking_status bs\n    ON b.booking_status_id_FK = bs.booking_status_id_PK;\n\n-- invoice → booking\nSELECT *\nFROM invoice i\nJOIN booking b\n    ON i.booking_id_FK = b.booking_id_PK;\n\n-- invoice → payment_method\nSELECT *\nFROM invoice i\nJOIN payment_method pm\n    ON i.payment_method_id_FK = pm.payment_method_id_PK;\n\n-- invoice → invoice_item\nSELECT *\nFROM invoice i\nJOIN invoice_item ii\n    ON i.invoice_id_PK = ii.invoice_id_FK;\n\n-- invoice_item → service_type\nSELECT *\nFROM invoice_item ii\nJOIN service_type st\n    ON ii.service_type_id_FK = st.service_type_id_PK;\n\n-- invoice → booking → guest\nSELECT *\nFROM invoice i\nJOIN booking b\n    ON i.booking_id_FK = b.booking_id_PK\nJOIN guest g\n    ON b.guest_id_FK = g.guest_id_PK;\n\n-- invoice → booking → room → hotel\nSELECT *\nFROM invoice i\nJOIN booking b\n    ON i.booking_id_FK = b.booking_id_PK\nJOIN room r\n    ON b.room_id_FK = r.room_id_PK\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK;\n\n-- invoice → payment_method → invoice_item → service_type\nSELECT *\nFROM invoice i\nJOIN payment_method pm\n    ON i.payment_method_id_FK = pm.payment_method_id_PK\nJOIN invoice_item ii\n    ON i.invoice_id_PK = ii.invoice_id_FK\nJOIN service_type st\n    ON ii.service_type_id_FK = st.service_type_id_PK;\n\n\n-- ============================================================\n-- 2) Complete JOIN query across almost the whole model\n-- ============================================================\n\nSELECT\n    b.booking_id_PK,\n    b.start_date,\n    b.end_date,\n    b.booking_date,\n    b.adults_number,\n    b.children_number,\n    b.with_pets,\n    b.booking_price,\n\n    bs.name AS booking_status,\n\n    g.guest_id_PK,\n    g.first_name AS guest_first_name,\n    g.last_name AS guest_last_name,\n    g.phone_number,\n    g.email_address,\n    g.passport_number,\n\n    ga.street AS guest_street,\n    ga.house_number AS guest_house_number,\n    ga.zip_code AS guest_zip_code,\n    ga.city AS guest_city,\n    ga.country AS guest_country,\n\n    r.room_id_PK,\n    r.room_number,\n    r.max_guests,\n\n    h.hotel_id_PK,\n    h.name AS hotel_name,\n    h.stars,\n    h.pets_allowed,\n    h.wheelchair_accessible,\n\n    ha.street AS hotel_street,\n    ha.house_number AS hotel_house_number,\n    ha.zip_code AS hotel_zip_code,\n    ha.city AS hotel_city,\n    ha.country AS hotel_country,\n\n    o.first_name AS owner_first_name,\n    o.last_name AS owner_last_name,\n\n    tc.name AS room_type_name,\n    rt.description AS room_type_description,\n\n    i.invoice_id_PK,\n    i.invoice_date,\n    i.currency,\n    i.paid_date,\n    i.total_price,\n\n    pm.name AS payment_method\n\nFROM booking b\nJOIN booking_status bs\n    ON b.booking_status_id_FK = bs.booking_status_id_PK\nJOIN guest g\n    ON b.guest_id_FK = g.guest_id_PK\nJOIN address ga\n    ON g.guest_address_id_FK = ga.address_id_PK\nJOIN room r\n    ON b.room_id_FK = r.room_id_PK\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nJOIN address ha\n    ON h.hotel_address_id_FK = ha.address_id_PK\nJOIN owner o\n    ON h.owner_id_FK = o.owner_id_PK\nJOIN room_type rt\n    ON r.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK\nLEFT JOIN invoice i\n    ON b.booking_id_PK = i.booking_id_FK\nLEFT JOIN payment_method pm\n    ON i.payment_method_id_FK = pm.payment_method_id_PK;\n\n\n-- ============================================================\n-- 3) Important bridge tables\n-- ============================================================\n\n-- Hotel and hotel facilities many-to-many\nSELECT\n    h.name AS hotel_name,\n    hf.name AS facility_name\nFROM hotel h\nJOIN hotel_has_facility hhf\n    ON h.hotel_id_PK = hhf.hotel_id_FK\nJOIN hotel_facility hf\n    ON hhf.hotel_facility_id_FK = hf.hotel_facility_id_PK;\n\n-- Room and room facilities many-to-many\nSELECT\n    r.room_number,\n    rf.name AS facility_name\nFROM room r\nJOIN room_has_facility rhf\n    ON r.room_id_PK = rhf.room_id_FK\nJOIN room_facility rf\n    ON rhf.room_facility_id_FK = rf.room_facility_id_PK;\n\n\n-- ============================================================\n-- 4) Complete room price join\n-- ============================================================\n\nSELECT\n    tc.name AS room_type,\n    sc.name AS season_name,\n    sc.valid_from,\n    sc.valid_to,\n    rp.price_per_night\nFROM room_price rp\nJOIN room_type rt\n    ON rp.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK\nJOIN season_code sc\n    ON rp.season_code_id_FK = sc.season_code_id_PK;\n',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_31

## Tables with Normalisation

In [ ]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_33 = _dntk.execute_sql(
  'PRAGMA foreign_keys = ON;\n\n-- ============================================================\n-- ADDRESS\n-- 3NF:\n-- Address data is stored separately.\n-- Hotels, owners and guests only reference addresses by foreign keys.\n-- This avoids duplicated address data.\n-- ============================================================\n\nCREATE TABLE address (\n    address_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    street VARCHAR(100) NOT NULL,\n    house_number VARCHAR(10) NOT NULL,\n    zip_code VARCHAR(10) NOT NULL,\n    city VARCHAR(50) NOT NULL,\n    country VARCHAR(50) NOT NULL\n);\n\n-- ============================================================\n-- OWNER\n-- 3NF:\n-- Owner data is separated from address data.\n-- The address is referenced by owner_address_id_FK.\n-- ============================================================\n\nCREATE TABLE owner (\n    owner_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    owner_address_id_FK INTEGER NOT NULL,\n    first_name VARCHAR(100) NOT NULL,\n    last_name VARCHAR(100) NOT NULL,\n\n    FOREIGN KEY (owner_address_id_FK)\n        REFERENCES address(address_id_PK)\n);\n\n-- ============================================================\n-- GUEST\n-- 3NF:\n-- Guest data is separated from address data.\n-- The address is referenced by guest_address_id_FK.\n-- ============================================================\n\nCREATE TABLE guest (\n    guest_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    guest_address_id_FK INTEGER NOT NULL,\n    first_name VARCHAR(100) NOT NULL,\n    last_name VARCHAR(100) NOT NULL,\n    phone_number VARCHAR(30),\n    email_address VARCHAR(100),\n    passport_number VARCHAR(50),\n\n    FOREIGN KEY (guest_address_id_FK)\n        REFERENCES address(address_id_PK)\n);\n\n-- ============================================================\n-- HOTEL\n-- 3NF:\n-- Hotel data references owner and address.\n-- Owner and address information is not repeated in the hotel table.\n-- ============================================================\n\nCREATE TABLE hotel (\n    hotel_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    owner_id_FK INTEGER NOT NULL,\n    hotel_address_id_FK INTEGER NOT NULL,\n    name VARCHAR(100) NOT NULL,\n    stars INTEGER NOT NULL,\n    pets_allowed INTEGER NOT NULL,\n    wheelchair_accessible INTEGER NOT NULL,\n\n    FOREIGN KEY (owner_id_FK)\n        REFERENCES owner(owner_id_PK),\n\n    FOREIGN KEY (hotel_address_id_FK)\n        REFERENCES address(address_id_PK)\n);\n\n-- ============================================================\n-- HOTEL FACILITY\n-- 1NF:\n-- Hotel facilities are not stored as a list inside the hotel table.\n-- Each facility is stored as one separate record.\n-- ============================================================\n\nCREATE TABLE hotel_facility (\n    hotel_facility_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    icon VARCHAR(50),\n    name VARCHAR(100) NOT NULL,\n    description VARCHAR(255)\n);\n\n-- ============================================================\n-- HOTEL HAS FACILITY\n-- 1NF / 3NF:\n-- A hotel can have multiple facilities.\n-- A facility can belong to multiple hotels.\n-- This many-to-many relationship is resolved through a junction table.\n-- ============================================================\n\nCREATE TABLE hotel_has_facility (\n    hotel_has_facility_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    hotel_id_FK INTEGER NOT NULL,\n    hotel_facility_id_FK INTEGER NOT NULL,\n\n    FOREIGN KEY (hotel_id_FK)\n        REFERENCES hotel(hotel_id_PK),\n\n    FOREIGN KEY (hotel_facility_id_FK)\n        REFERENCES hotel_facility(hotel_facility_id_PK)\n);\n\n-- ============================================================\n-- TYPE CODE\n-- 2NF / 3NF:\n-- Type names are stored separately to avoid repeated text values.\n-- Example: Single Room, Double Room, Studio, Family Room, Suite.\n-- ============================================================\n\nCREATE TABLE type_code (\n    type_code_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    name VARCHAR(100) NOT NULL\n);\n\n-- ============================================================\n-- ROOM TYPE\n-- 2NF:\n-- Room type descriptions are stored separately from individual rooms.\n-- The description depends on the room type, not on each room.\n-- ============================================================\n\nCREATE TABLE room_type (\n    room_type_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    type_code_id_FK INTEGER NOT NULL,\n    description VARCHAR(255) NOT NULL,\n\n    FOREIGN KEY (type_code_id_FK)\n        REFERENCES type_code(type_code_id_PK)\n);\n\n-- ============================================================\n-- ROOM\n-- 2NF:\n-- The room table only stores data that belongs to the individual room.\n-- Type-specific information is stored in room_type.\n-- ============================================================\n\nCREATE TABLE room (\n    room_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    hotel_id_FK INTEGER NOT NULL,\n    room_type_id_FK INTEGER NOT NULL,\n    room_number VARCHAR(20) NOT NULL,\n    max_guests INTEGER NOT NULL,\n\n    FOREIGN KEY (hotel_id_FK)\n        REFERENCES hotel(hotel_id_PK),\n\n    FOREIGN KEY (room_type_id_FK)\n        REFERENCES room_type(room_type_id_PK)\n);\n\n-- ============================================================\n-- ROOM FACILITY\n-- 1NF:\n-- Room facilities are stored separately.\n-- They are not stored as comma-separated values in the room table.\n-- ============================================================\n\nCREATE TABLE room_facility (\n    room_facility_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    icon VARCHAR(50),\n    name VARCHAR(100) NOT NULL,\n    description VARCHAR(255)\n);\n\n-- ============================================================\n-- ROOM HAS FACILITY\n-- 1NF / 3NF:\n-- A room can have multiple facilities.\n-- A facility can belong to multiple rooms.\n-- This many-to-many relationship is resolved through a junction table.\n-- ============================================================\n\nCREATE TABLE room_has_facility (\n    room_has_facility_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    room_id_FK INTEGER NOT NULL,\n    room_facility_id_FK INTEGER NOT NULL,\n\n    FOREIGN KEY (room_id_FK)\n        REFERENCES room(room_id_PK),\n\n    FOREIGN KEY (room_facility_id_FK)\n        REFERENCES room_facility(room_facility_id_PK)\n);\n\n-- ============================================================\n-- SEASON CODE\n-- 3NF:\n-- Season information is stored separately.\n-- Room prices reference the season instead of storing season details directly.\n-- ============================================================\n\nCREATE TABLE season_code (\n    season_code_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    name VARCHAR(100) NOT NULL,\n    valid_from DATE NOT NULL,\n    valid_to DATE NOT NULL\n);\n\n-- ============================================================\n-- ROOM PRICE\n-- 3NF:\n-- Room prices depend on room type and season.\n-- They are not stored directly in the room table.\n-- ============================================================\n\nCREATE TABLE room_price (\n    room_price_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    season_code_id_FK INTEGER NOT NULL,\n    room_type_id_FK INTEGER NOT NULL,\n    price_per_night DECIMAL(10,2) NOT NULL,\n\n    FOREIGN KEY (season_code_id_FK)\n        REFERENCES season_code(season_code_id_PK),\n\n    FOREIGN KEY (room_type_id_FK)\n        REFERENCES room_type(room_type_id_PK)\n);\n\n-- ============================================================\n-- BOOKING STATUS\n-- 3NF:\n-- Booking statuses are stored as master data.\n-- This avoids inconsistent status values.\n-- ============================================================\n\nCREATE TABLE booking_status (\n    booking_status_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    name VARCHAR(100) NOT NULL\n);\n\n-- ============================================================\n-- BOOKING\n-- 3NF:\n-- Booking references guest, room and booking status.\n-- Guest, room and status data are not repeated in this table.\n--\n-- booking_price is stored as a historical snapshot value.\n-- This documents the price at the time of booking.\n-- ============================================================\n\nCREATE TABLE booking (\n    booking_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    guest_id_FK INTEGER NOT NULL,\n    booking_status_id_FK INTEGER NOT NULL,\n    room_id_FK INTEGER NOT NULL,\n    start_date DATE NOT NULL,\n    end_date DATE NOT NULL,\n    booking_date DATE NOT NULL,\n    adults_number INTEGER NOT NULL,\n    children_number INTEGER NOT NULL,\n    with_pets INTEGER NOT NULL,\n    booking_price DECIMAL(10,2) NOT NULL,\n\n    FOREIGN KEY (guest_id_FK)\n        REFERENCES guest(guest_id_PK),\n\n    FOREIGN KEY (booking_status_id_FK)\n        REFERENCES booking_status(booking_status_id_PK),\n\n    FOREIGN KEY (room_id_FK)\n        REFERENCES room(room_id_PK)\n);\n\n-- ============================================================\n-- PAYMENT METHOD\n-- 3NF:\n-- Payment methods are stored separately as master data.\n-- This avoids repeated and inconsistent payment method values.\n-- ============================================================\n\nCREATE TABLE payment_method (\n    payment_method_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    name VARCHAR(100) NOT NULL\n);\n\n-- ============================================================\n-- INVOICE\n-- 3NF:\n-- Invoice data is separated from booking and invoice items.\n-- One booking can have one invoice, and one invoice can have several items.\n--\n-- total_price is stored as a historical invoice snapshot value.\n-- ============================================================\n\nCREATE TABLE invoice (\n    invoice_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    booking_id_FK INTEGER NOT NULL,\n    payment_method_id_FK INTEGER,\n    invoice_date DATE NOT NULL,\n    currency VARCHAR(10) NOT NULL,\n    paid_date DATE,\n    total_price DECIMAL(10,2) NOT NULL,\n\n    FOREIGN KEY (booking_id_FK)\n        REFERENCES booking(booking_id_PK),\n\n    FOREIGN KEY (payment_method_id_FK)\n        REFERENCES payment_method(payment_method_id_PK)\n);\n\n-- ============================================================\n-- SERVICE TYPE\n-- 3NF:\n-- Service types are stored separately as master data.\n-- This avoids repeating values such as Accommodation, Food,\n-- Service or Leisure in each invoice item.\n-- ============================================================\n\nCREATE TABLE service_type (\n    service_type_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    name VARCHAR(100) NOT NULL\n);\n\n-- ============================================================\n-- INVOICE ITEM\n-- 3NF:\n-- Invoice items reference invoice and service_type.\n-- The service type text is not stored directly in invoice_item.\n-- This avoids redundancy and supports consistent invoice line items.\n-- ============================================================\n\nCREATE TABLE invoice_item (\n    invoice_item_id_PK INTEGER PRIMARY KEY AUTOINCREMENT,\n    invoice_id_FK INTEGER NOT NULL,\n    service_type_id_FK INTEGER NOT NULL,\n    description VARCHAR(255) NOT NULL,\n    quantity INTEGER NOT NULL,\n    unit_price DECIMAL(10,2) NOT NULL,\n\n    FOREIGN KEY (invoice_id_FK)\n        REFERENCES invoice(invoice_id_PK),\n\n    FOREIGN KEY (service_type_id_FK)\n        REFERENCES service_type(service_type_id_PK)\n);',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_33

### Run ATTACH only once\. If you get an error saying that the database already exists, execute USE memory; followed by DETACH HotelDB;\. After that, run the ATTACH statement again\.

In [103]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_23 = _dntk.execute_sql(
  'INSTALL sqlite;\nLOAD sqlite;\n\nATTACH \'sqlite/5. HotelWithTestJoinNormalisation.db\'\nAS HotelDB (TYPE SQLITE);\n\nUSE HotelDB;\n\nSHOW TABLES;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_23

,name
0,address
1,booking
2,booking_status
3,guest
4,hotel
5,hotel_facility
6,hotel_has_facility
7,invoice
8,invoice_item
9,owner


DETACH

In [109]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_24 = _dntk.execute_sql(
  'USE memory;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_24

,Success


In [ ]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_53 = _dntk.execute_sql(
  'DETACH HotelDB;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_53

# AS A USER

## User Story 1a

I want to search for all hotels in a city\.

Short Explanation

Returns all hotels located in a specific city\.

In [7]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  '    SELECT \n        h.name AS hotel_name,\n        a.city,\n        h.stars\n    FROM hotel h\n    JOIN address a\n        ON h.hotel_address_id_FK = a.address_id_PK\n    WHERE a.city = \'St. Moritz\'\n    ORDER BY h.name;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

,hotel_name,city,stars
0,Grand Snow Palace,St. Moritz,5



Short Interpretation

This query returns all hotels in St\. Moritz, including their name and star rating\.

## User Story 1b

I want to search for all hotels in a city sorted by stars\.

Short Explanation

Returns hotels in a city ordered by their star rating\.

In [9]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT \n    h.name AS hotel_name,\n    a.city,\n    h.stars\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nWHERE a.city = \'St. Moritz\'\nORDER BY h.stars DESC, h.name ASC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

,hotel_name,city,stars
0,Grand Snow Palace,St. Moritz,5


Short Interpretation

Hotels in Davos are sorted by stars \(highest first\)

## User Story 1c 

I want to search for hotels in a city that can host my number of guests\.

Short Explanation

Returns hotels that have at least one room with sufficient capacity\.

In [91]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_32 = _dntk.execute_sql(
  'SELECT\n    h.name AS hotel_name,\n    a.city,\n    r.max_guests,\n    h.stars\nFROM hotel h\nINNER JOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nINNER JOIN room r\n    ON h.hotel_id_PK = r.hotel_id_FK\nWHERE a.city = \'St. Moritz\'\n  AND r.max_guests >= 1\nORDER BY h.name;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_32

,hotel_name,city,max_guests,stars
0,Engadin Comfort Stay,St. Moritz,3,3
1,Engadin Comfort Stay,St. Moritz,2,3
2,Engadin Comfort Stay,St. Moritz,1,3
3,Grand Snow Palace,St. Moritz,4,5
4,Grand Snow Palace,St. Moritz,3,5
5,Grand Snow Palace,St. Moritz,2,5


Short Interpretation

Shows all hotels in St\. Moritz that have at least one room for 2 guests\.

## User Story 1d

I want to see only hotels that have available rooms during my stay\.

Short Explanation

Checks if a room is available within a given time period\.

In [13]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_2 = _dntk.execute_sql(
  'SELECT DISTINCT\n    h.name AS hotel_name,\n    a.city,\n    h.stars\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nJOIN room r\n    ON h.hotel_id_PK = r.hotel_id_FK\nWHERE a.city = \'Davos\'\n  AND r.max_guests >= 2\n  AND NOT EXISTS (\n      SELECT 1\n      FROM booking b\n      JOIN booking_status bs\n          ON b.booking_status_id_FK = bs.booking_status_id_PK\n      WHERE b.room_id_FK = r.room_id_PK\n        AND bs.name <> \'Cancelled\'\n        AND b.start_date < \'2026-12-27\'\n        AND b.end_date > \'2026-12-23\'\n  )\nORDER BY h.name;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_2

,hotel_name,city,stars
0,Davos Family Escape,Davos,4


Short Interpretation

Returns hotels in Davos with at least one available room for 2 guests between 23\.12\.2026 and 27\.12\.2026\.

## User Story 1e

I want to see name, address, and stars per hotel\.

Short Explanation

Displays key hotel information\.

In [15]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_34 = _dntk.execute_sql(
  'SELECT\n    h.name AS hotel_name,\n    a.street,\n    a.house_number,\n    a.zip_code,\n    a.city,\n    a.country,\n    h.stars\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nORDER BY h.name;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_34

,hotel_name,street,house_number,zip_code,city,country,stars
0,Alpenblick Lodge,Promenade,101,7270,Davos Platz,Switzerland,4
1,Alpenblick Lodge,Bahnhofstrasse,25,7260,Davos,Switzerland,4
2,Alpenblick Lodge,Promenade,101,7270,Davos Platz,Switzerland,4
3,Alpenblick Resort & Spa,Promenade,101,7270,Davos Platz,Switzerland,5
4,Chalet Panorama Gstaad,Wispilenstrasse,3,3780,Gstaad,Switzerland,4
5,Davos Family Escape,Dorfstrasse,8,7260,Davos,Switzerland,4
6,Grand Snow Palace,Via Serlas,9,7500,St. Moritz,Switzerland,5
7,Lakeview Lodge Interlaken,Höheweg,41,3800,Interlaken,Switzerland,4


Short Interpretation

Returns hotel name, full address, and star rating\.

## User Story 1f

I want to select a hotel and view its details\.

Short Explanation

Displays detailed information for a specific hotel\.

In [93]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_35 = _dntk.execute_sql(
  'SELECT\n    h.name AS hotel_name,\n    h.stars,\n    h.pets_allowed,\n    h.wheelchair_accessible,\n    a.street,\n    a.house_number,\n    a.zip_code,\n    a.city,\n    a.country\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nWHERE h.name = \'Alpine Peak Resort\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_35

,hotel_name,stars,pets_allowed,wheelchair_accessible,street,house_number,zip_code,city,country
0,Alpine Peak Resort,5,1,1,Promenade,101,7270,Davos Platz,Switzerland


Short Interpretation

Returns full details of the hotel\.

## User Story 2a

I want to see room type, capacity, description, facilities and price per night\.

Short Explanation

Displays detailed room information including facilities and pricing\.

In [21]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_18 = _dntk.execute_sql(
  'SELECT \n    h.name AS hotel_name,\n    r.room_id_PK,\n    r.room_number,\n    tc.name AS room_type,\n    r.max_guests,\n    rt.description,\n    rp.price_per_night,\n    sc.name AS season,\n    sc.valid_from,\n    GROUP_CONCAT(rf.name, \', \') AS room_facilities\nFROM room r\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nJOIN room_type rt\n    ON r.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK\nJOIN room_price rp\n    ON rt.room_type_id_PK = rp.room_type_id_FK\nJOIN season_code sc\n    ON rp.season_code_id_FK = sc.season_code_id_PK\nLEFT JOIN room_has_facility rhf\n    ON r.room_id_PK = rhf.room_id_FK\nLEFT JOIN room_facility rf\n    ON rhf.room_facility_id_FK = rf.room_facility_id_PK\nWHERE h.hotel_id_PK = 1\nGROUP BY \n    h.name,\n    r.room_id_PK,\n    r.room_number,\n    tc.name,\n    r.max_guests,\n    rt.description,\n    rp.price_per_night,\n    sc.name,\n    sc.valid_from\nORDER BY \n    r.room_number,\n    sc.valid_from;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_18

,hotel_name,room_id_PK,room_number,room_type,max_guests,description,price_per_night,season,valid_from,room_facilities
0,Alpenblick Resort & Spa,1,101,Single Room,1,Single room with one bed for one guest,110.0,Shoulder Season 2026,2026-03-16,"TV, Shower, Desk, Safe"
1,Alpenblick Resort & Spa,1,101,Single Room,1,Single room with one bed for one guest,130.0,Summer 2026,2026-06-01,"TV, Shower, Desk, Safe"
2,Alpenblick Resort & Spa,1,101,Single Room,1,Single room with one bed for one guest,120.0,Autumn 2026,2026-09-16,"TV, Shower, Desk, Safe"
3,Alpenblick Resort & Spa,1,101,Single Room,1,Single room with one bed for one guest,180.0,Winter Peak 2026,2026-12-15,"TV, Shower, Desk, Safe"
4,Alpenblick Resort & Spa,2,102,Double Room,2,Double room with a double bed or twin beds,165.0,Shoulder Season 2026,2026-03-16,"TV, Balcony, Shower, Desk, Safe"
5,Alpenblick Resort & Spa,2,102,Double Room,2,Double room with a double bed or twin beds,190.0,Summer 2026,2026-06-01,"TV, Balcony, Shower, Desk, Safe"
6,Alpenblick Resort & Spa,2,102,Double Room,2,Double room with a double bed or twin beds,175.0,Autumn 2026,2026-09-16,"TV, Balcony, Shower, Desk, Safe"
7,Alpenblick Resort & Spa,2,102,Double Room,2,Double room with a double bed or twin beds,260.0,Winter Peak 2026,2026-12-15,"TV, Balcony, Shower, Desk, Safe"
8,Alpenblick Resort & Spa,3,201,Suite,4,Suite with separate living area and premium co...,450.0,Shoulder Season 2026,2026-03-16,"TV, Balcony, Minibar, Bathtub, Safe, Coffee Ma..."
9,Alpenblick Resort & Spa,3,201,Suite,4,Suite with separate living area and premium co...,520.0,Summer 2026,2026-06-01,"TV, Balcony, Minibar, Bathtub, Safe, Coffee Ma..."


Short Interpretation

Shows all rooms of hotel with type, capacity, description, seasonal prices, and facilities\.

## User Story 2b

I want to see only available rooms\.

Short Explanation

Filters rooms that are not booked in the selected time period\.

In [23]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_8 = _dntk.execute_sql(
  'SELECT \n    r.room_number,\n    tc.name AS room_type,\n    r.max_guests,\n    rt.description\nFROM room r\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nJOIN room_type rt\n    ON r.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK\nWHERE h.hotel_id_PK = 1\n  AND NOT EXISTS (\n      SELECT 1\n      FROM booking b\n      JOIN booking_status bs\n          ON b.booking_status_id_FK = bs.booking_status_id_PK\n      WHERE b.room_id_FK = r.room_id_PK\n        AND bs.name <> \'Cancelled\'\n        AND b.start_date < \'2026-12-27\'\n        AND b.end_date > \'2026-12-23\'\n  )\nORDER BY r.room_number;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_8

,room_number,room_type,max_guests,description
0,101,Single Room,1,Single room with one bed for one guest
1,102,Double Room,2,Double room with a double bed or twin beds
2,201,Suite,4,Suite with separate living area and premium co...
3,202,Family Room,5,Family room with several sleeping options


Short Interpretation

Shows only rooms in hotel that are available between 23\.12\.2026 and 27\.12\.2026\.

## User Story 3

I want to book a room in a specific hotel\.

Short Explanation

Checks whether rooms in a selected hotel are available for the requested booking period\.

In [25]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_36 = _dntk.execute_sql(
  'SELECT\n    h.name AS hotel_name,\n    r.room_id_PK,\n    r.room_number,\n    r.max_guests,\n    CASE\n        WHEN EXISTS (\n            SELECT 1\n            FROM booking b\n            JOIN booking_status bs\n                ON b.booking_status_id_FK = bs.booking_status_id_PK\n            WHERE b.room_id_FK = r.room_id_PK\n              AND bs.name <> \'Cancelled\'\n              AND b.start_date < \'2026-12-27\'\n              AND b.end_date > \'2026-12-23\'\n        )\n        THEN \'Not available\'\n        ELSE \'Available\'\n    END AS availability\nFROM room r\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nWHERE h.name = \'Grand Snow Palace\'\nORDER BY r.room_number;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_36

,hotel_name,room_id_PK,room_number,max_guests,availability
0,Grand Snow Palace,5,301,2,Available
1,Grand Snow Palace,6,302,3,Available
2,Grand Snow Palace,7,401,4,Not available


Short Interpretation

Returns all rooms of the selected hotel and shows whether each room is available or not for the selected date range\.

# AS AN ADMIN USER

## Admin User Story 1a

I want to add new hotels to the system\.

Short Explanation

Adds a new hotel called Alpenblick Lodge to the hotel reservation system\.

The new hotel is located at: Bahnhofstrasse 25, 7260 Davos, Switzerland

The hotel has: 

- 4 stars

- Pets allowed 

- Wheelchair accessible

- Owner ID 1

In [37]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_37 = _dntk.execute_sql(
  'INSERT INTO address (\n    street,\n    house_number,\n    zip_code,\n    city,\n    country\n)\nVALUES (\n    \'Bahnhofstrasse\',\n    \'25\',\n    \'7260\',\n    \'Davos\',\n    \'Switzerland\'\n);\n\nINSERT INTO hotel (\n    owner_id_FK,\n    hotel_address_id_FK,\n    name,\n    stars,\n    pets_allowed,\n    wheelchair_accessible\n)\nSELECT\n    1,\n    address_id_PK,\n    \'Alpenblick Lodge\',\n    4,\n    1,\n    1\nFROM address\nWHERE street = \'Bahnhofstrasse\'\n    AND house_number = \'25\'\n    AND zip_code = \'7260\'\n    AND city = \'Davos\'\n    AND country = \'Switzerland\'\nORDER BY address_id_PK DESC\nLIMIT 1;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_37

,Count
0,1


In [39]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_38 = _dntk.execute_sql(
  'SELECT\n    h.hotel_id_PK,\n    h.name AS hotel_name,\n    h.stars,\n    h.pets_allowed,\n    h.wheelchair_accessible,\n    a.street,\n    a.house_number,\n    a.zip_code,\n    a.city,\n    a.country\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nWHERE h.name = \'Alpenblick Lodge\';',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_38

,hotel_id_PK,hotel_name,stars,pets_allowed,wheelchair_accessible,street,house_number,zip_code,city,country
0,7,Alpenblick Lodge,4,1,1,Bahnhofstrasse,25,7260,Davos,Switzerland


Creates the new hotel Alpenblick Lodge and links it to its address in Davos\.

First, the address Bahnhofstrasse 25, 7260 Davos, Switzerland is inserted into the address table\. After that, the hotel Alpenblick Lodge is inserted into the hotel table and connected to this address through hotel\_address\_id\_FK\.

## Admin User Story 1b

I want to delete hotel\.

Short Explanation

Deletes a selected hotel from the hotel reservation system\. In this example, the hotel with the ID 6 is deleted from the system\.

Check before deleting

In [41]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_40 = _dntk.execute_sql(
  'SELECT\n    h.hotel_id_PK,\n    h.name AS hotel_name,\n    h.stars,\n    a.street,\n    a.house_number,\n    a.zip_code,\n    a.city,\n    a.country\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nWHERE h.hotel_id_PK = 6;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_40

,hotel_id_PK,hotel_name,stars,street,house_number,zip_code,city,country
0,6,Engadin Comfort Stay,3,Via Maistra,22,7500,St. Moritz,Switzerland


Check Interpretation

Returns the hotel with ID 6 before it is deleted\. This is important to make sure that the correct hotel is selected\.

Deleting

In [43]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_41 = _dntk.execute_sql(
  'DELETE FROM hotel\nWHERE hotel_id_PK = 6;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_41

,Count
0,1


Short Interpretation

Deletes the hotel with the ID 6 from the hotel table\. 

An admin user may need to remove hotels from the system if they are no longer available, were entered incorrectly or should no longer be shown to guests\.The hotel is deleted by using its primary key hotel\_id\_PK, because the ID uniquely identifies one specific hotel\.

After deleting

In [73]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_51 = _dntk.execute_sql(
  'SELECT\n    h.hotel_id_PK,\n    h.name AS hotel_name,\n    h.stars,\n    a.street,\n    a.house_number,\n    a.zip_code,\n    a.city,\n    a.country\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nWHERE h.hotel_id_PK = 6;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_51

,hotel_id_PK,hotel_name,stars,street,house_number,zip_code,city,country


Short Interpretation

The query checks whether the hotel with the ID 6 still exists after the delete operation\. Since no row is returned, the hotel was successfully deleted from the hotel table\.

## Admin User Story 1c

I want to update hotel information\.

Short Explanation

Updates existing hotel information in the hotel reservation system\. In this example, the hotel with the ID 1 is updated\. The hotel name is changed to Alpenblick Resort & Spa and the star rating is changed to 4 stars\.

Check before updating

In [45]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_42 = _dntk.execute_sql(
  'SELECT\n    h.hotel_id_PK,\n    h.name AS hotel_name,\n    h.stars,\n    h.pets_allowed,\n    h.wheelchair_accessible\nFROM hotel h\nWHERE h.hotel_id_PK = 1;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_42

,hotel_id_PK,hotel_name,stars,pets_allowed,wheelchair_accessible
0,1,Alpine Peak Resort,5,1,1


Check Interpretation

Returns the current information of the hotel with ID 1 before the update\. This helps to verify which hotel will be changed\.

Updated

In [77]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_43 = _dntk.execute_sql(
  'UPDATE hotel\nSET\n    name = \'Alpenblick Resort & Spa\',\n    stars = 4\nWHERE hotel_id_PK = 1;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_43

,Count
0,1


Short Interpretation

Updates the hotel with ID 1 by changing its name and star rating\. An admin user may need to update hotel information when hotel details change, for example after a rebranding, renovation or a new star classification\.

The hotel is updated using the primary key hotel\_id\_PK, because this ID uniquely identifies one specific hotel\. This prevents accidentally updating several hotels with a similar name\.

After updating

In [79]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_52 = _dntk.execute_sql(
  'SELECT\n    h.hotel_id_PK,\n    h.name AS hotel_name,\n    h.stars,\n    h.pets_allowed,\n    h.wheelchair_accessible\nFROM hotel h\nWHERE h.hotel_id_PK = 1;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_52

,hotel_id_PK,hotel_name,stars,pets_allowed,wheelchair_accessible
0,1,Alpenblick Resort & Spa,4,1,1


Short Interpretation

The result shows that the hotel name is now Alpenblick Resort & Spa and the star rating is 4\. This confirms that the hotel information was successfully updated\.

## Admin User Story 2

I want to see all bookings across all hotels\.

Short Explanation

Displays a complete overview of all bookings in the hotel reservation system\. 

The overview includes the booking ID, hotel name, room number, customer name, booking status, booking dates, number of guests and booking price\.

In [53]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_12 = _dntk.execute_sql(
  'SELECT \n    b.booking_id_PK,\n    h.name AS hotel_name,\n    r.room_number,\n    c.first_name || \' \' || c.last_name AS customer_name,\n    bs.name AS booking_status,\n    b.start_date,\n    b.end_date,\n    b.booking_date,\n    b.adults_number,\n    b.children_number,\n    b.booking_price\nFROM booking b\nJOIN guest c\n    ON b.guest_id_FK = c.guest_id_PK\nJOIN booking_status bs\n    ON b.booking_status_id_FK = bs.booking_status_id_PK\nJOIN room r\n    ON b.room_id_FK = r.room_id_PK\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nORDER BY b.booking_id_PK;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_12

,booking_id_PK,hotel_name,room_number,customer_name,booking_status,start_date,end_date,booking_date,adults_number,children_number,booking_price
0,1,Alpenblick Resort & Spa,102,Anna Schneider,Completed,2026-01-10,2026-01-14,2025-11-20,2,0,1040.0
1,2,Grand Snow Palace,301,David Mueller,Cancelled,2026-02-05,2026-02-09,2025-12-18,2,0,1040.0
2,3,Chalet Panorama Gstaad,B20,Elena Rossi,Completed,2026-03-01,2026-03-06,2026-01-08,2,2,1450.0
3,4,Lakeview Lodge Interlaken,20,Marc Dubois,Checked-in,2026-04-20,2026-04-25,2026-03-02,2,1,1100.0
4,6,Grand Snow Palace,401,Jonas Weber,Completed,2026-12-22,2026-12-27,2026-09-30,2,1,3450.0
5,7,Davos Family Escape,D2,Sarah Meier,Confirmed,2026-08-03,2026-08-08,2026-06-01,2,2,1600.0
6,8,Lakeview Lodge Interlaken,11,Paul Hofmann,Pending,2026-10-10,2026-10-12,2026-10-01,1,0,240.0
7,9,Alpenblick Resort & Spa,201,Laura Bianchi,Completed,2026-01-15,2026-01-18,2025-12-05,2,1,2070.0


Short Interpretation

Returns all bookings from all hotels in one overview\. 

## Admin User Story 3

I want to update customer information\.

Short Explanation

Updates existing customer information in the hotel reservation system\.  In this example, the phone number of the customer with ID 3 is changed to: \+41 79 555 44 33

Check before updating

In [55]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_44 = _dntk.execute_sql(
  'SELECT\n    guest_id_PK,\n    first_name,\n    last_name,\n    email_address,\n    phone_number\nFROM guest\nWHERE guest_id_PK = 3;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_44

,guest_id_PK,first_name,last_name,email_address,phone_number
0,3,Elena,Rossi,elena.rossi@example.com,+41794443322


Check Interpretation

Returns the current information of guest 3 before the update\. This helps to verify which guest will be changed\.

Updated

In [57]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_45 = _dntk.execute_sql(
  'UPDATE guest\nSET phone_number = \'+41 79 555 44 33\'\nWHERE guest_id_PK = 3;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_45

,Count
0,1


Short Interpretation

Updates the phone number of the guest with ID 3\. Only the phone number is changed\. All other guest information remains unchanged\.

Check after updating

In [59]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_46 = _dntk.execute_sql(
  'SELECT\n    guest_id_PK,\n    first_name,\n    last_name,\n    email_address,\n    phone_number\nFROM guest\nWHERE guest_id_PK = 3;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_46

,guest_id_PK,first_name,last_name,email_address,phone_number
0,3,Elena,Rossi,elena.rossi@example.com,+41 79 555 44 33


Short Interpretation

Returns the updated guest information\. The result should now show the new phone number \+41 79 555 44 33 for guest 3\.

## ADDITIONAL USEFUL QUERIES

## Additional Query 1

### Unpaid invoices

I want to see all unpaid invoices

Short Explanation

Displays all invoices that have not been paid yet\. The query shows the invoice ID, hotel name, guest name, invoice date, total price, currency, and payment method\.

In [61]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_50 = _dntk.execute_sql(
  'SELECT\n    i.invoice_id_PK,\n    h.name AS hotel_name,\n    g.first_name || \' \' || g.last_name AS guest_name,\n    i.invoice_date,\n    i.total_price,\n    i.currency,\n    pm.name AS payment_method\nFROM invoice i\nJOIN booking b\n    ON i.booking_id_FK = b.booking_id_PK\nJOIN guest g\n    ON b.guest_id_FK = g.guest_id_PK\nJOIN room r\n    ON b.room_id_FK = r.room_id_PK\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nJOIN payment_method pm\n    ON i.payment_method_id_FK = pm.payment_method_id_PK\nWHERE i.paid_date IS NULL\nORDER BY i.invoice_date;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_50

,invoice_id_PK,hotel_name,guest_name,invoice_date,total_price,currency,payment_method
0,3,Lakeview Lodge Interlaken,Marc Dubois,2026-04-25,1175.0,CHF,Payment Slip


Short Interpretation

Returns all invoices where the paid\_date is empty\. This means the invoice has not been paid yet\. The result helps the admin user identify open payments and see which guest, hotel, booking, and payment method are connected to each unpaid invoice\.

### Hotels with ski storage

I want to see only hotels that have ski storage\.

Short Explanation

LIsts all hotels that offer ski storage as a hotel facility\.

In [63]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_17 = _dntk.execute_sql(
  'SELECT DISTINCT\n    h.hotel_id_PK,\n    h.name AS hotel_name,\n    a.city\nFROM hotel h\nJOIN address a\n    ON h.hotel_address_id_FK = a.address_id_PK\nJOIN hotel_has_facility hhf\n    ON h.hotel_id_PK = hhf.hotel_id_FK\nJOIN hotel_facility hf\n    ON hhf.hotel_facility_id_FK = hf.hotel_facility_id_PK\nWHERE hf.name = \'Ski Storage\'\nORDER BY h.name;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_17

,hotel_id_PK,hotel_name,city
0,1,Alpenblick Resort & Spa,Davos Platz
1,3,Chalet Panorama Gstaad,Gstaad
2,5,Davos Family Escape,Davos
3,2,Grand Snow Palace,St. Moritz


Short Interpretation

Lists all hotels that offer ski storage\.

### Rooms with bathtub

I want to see only rooms that have a bathtub\.

Short Explanation

List all hotels whose rooms offer a bathtub as a room facility

In [65]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_16 = _dntk.execute_sql(
  'SELECT \n    h.name AS hotel_name,\n    r.room_number,\n    tc.name AS room_type\nFROM room r\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nJOIN room_type rt\n    ON r.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK\nJOIN room_has_facility rhf\n    ON r.room_id_PK = rhf.room_id_FK\nJOIN room_facility rf\n    ON rhf.room_facility_id_FK = rf.room_facility_id_PK\nWHERE rf.name = \'Bathtub\'\nORDER BY h.name, r.room_number;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_16

,hotel_name,room_number,room_type
0,Alpenblick Resort & Spa,201,Suite
1,Alpenblick Resort & Spa,202,Family Room
2,Grand Snow Palace,401,Suite


Short Interpretation

Shows all rooms that have a bathtub\.

## Additional  Query 2

I want to compare room prices across different season codes\. 

Short Explanation

Creates a view that shows room prices across different seasons\. This makes it easier to compare how the price per night changes depending on the season\. I want to compare room prices across different season codes\.

Create View

In [67]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_48 = _dntk.execute_sql(
  'CREATE VIEW view_room_season_price AS\nSELECT\n    r.room_id_PK,\n    r.room_number,\n    h.name AS hotel_name,\n    tc.name AS room_type,\n    rt.description AS room_description,\n    sc.name AS season_name,\n    sc.valid_from,\n    sc.valid_to,\n    rp.price_per_night\nFROM room r\nJOIN hotel h\n    ON r.hotel_id_FK = h.hotel_id_PK\nJOIN room_type rt\n    ON r.room_type_id_FK = rt.room_type_id_PK\nJOIN type_code tc\n    ON rt.type_code_id_FK = tc.type_code_id_PK\nJOIN room_price rp\n    ON rp.room_type_id_FK = rt.room_type_id_PK\nJOIN season_code sc\n    ON rp.season_code_id_FK = sc.season_code_id_PK;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_48

,Count


If an error message appears saying that the view already exists, the existing view must first be removed before creating it again\. This can be done with DROP VIEW IF EXISTS view\_room\_season\_price;\.

In [1]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_39 = _dntk.execute_sql(
  'DROP VIEW IF EXISTS view_room_season_price;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_39

Show View

In [69]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_47 = _dntk.execute_sql(
  'SELECT\n    room_id_PK,\n    room_number,\n    hotel_name,\n    room_type,\n    room_description,\n    season_name,\n    valid_from,\n    valid_to,\n    price_per_night\nFROM view_room_season_price\nORDER BY\n    hotel_name,\n    room_number,\n    valid_from;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_47

,room_id_PK,room_number,hotel_name,room_type,room_description,season_name,valid_from,valid_to,price_per_night
0,1,101,Alpenblick Resort & Spa,Single Room,Single room with one bed for one guest,Shoulder Season 2026,2026-03-16,2026-05-31,110.0
1,1,101,Alpenblick Resort & Spa,Single Room,Single room with one bed for one guest,Summer 2026,2026-06-01,2026-09-15,130.0
2,1,101,Alpenblick Resort & Spa,Single Room,Single room with one bed for one guest,Autumn 2026,2026-09-16,2026-12-14,120.0
3,1,101,Alpenblick Resort & Spa,Single Room,Single room with one bed for one guest,Winter Peak 2026,2026-12-15,2027-03-15,180.0
4,2,102,Alpenblick Resort & Spa,Double Room,Double room with a double bed or twin beds,Shoulder Season 2026,2026-03-16,2026-05-31,165.0
5,2,102,Alpenblick Resort & Spa,Double Room,Double room with a double bed or twin beds,Summer 2026,2026-06-01,2026-09-15,190.0
6,2,102,Alpenblick Resort & Spa,Double Room,Double room with a double bed or twin beds,Autumn 2026,2026-09-16,2026-12-14,175.0
7,2,102,Alpenblick Resort & Spa,Double Room,Double room with a double bed or twin beds,Winter Peak 2026,2026-12-15,2027-03-15,260.0
8,3,201,Alpenblick Resort & Spa,Suite,Suite with separate living area and premium co...,Shoulder Season 2026,2026-03-16,2026-05-31,450.0
9,3,201,Alpenblick Resort & Spa,Suite,Suite with separate living area and premium co...,Summer 2026,2026-06-01,2026-09-15,520.0


Short Interpretation

Returns room prices across different season periods\.The result shows the hotel name, room number, room type, room description, season name, validity period, and price per night\. This makes seasonal price differences visible and easier to compare\.

## Subquery

I want to see room prices that are above the average seasonal room price\.

Short Explanation 

Shows all room prices that are higher than the average room price across all seasons\. This helps to identify rooms or season periods with above\-average prices\.

In [71]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_49 = _dntk.execute_sql(
  'SELECT\n    room_id_PK,\n    room_number,\n    hotel_name,\n    room_type,\n    season_name,\n    price_per_night\nFROM view_room_season_price\nWHERE price_per_night > (\n    SELECT AVG(price_per_night)\n    FROM view_room_season_price\n)\nORDER BY price_per_night DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_49

,room_id_PK,room_number,hotel_name,room_type,season_name,price_per_night
0,3,201,Alpenblick Resort & Spa,Suite,Winter Peak 2026,690.0
1,7,401,Grand Snow Palace,Suite,Winter Peak 2026,690.0
2,3,201,Alpenblick Resort & Spa,Suite,Summer 2026,520.0
3,7,401,Grand Snow Palace,Suite,Summer 2026,520.0
4,3,201,Alpenblick Resort & Spa,Suite,Autumn 2026,470.0
5,7,401,Grand Snow Palace,Suite,Autumn 2026,470.0
6,3,201,Alpenblick Resort & Spa,Suite,Shoulder Season 2026,450.0
7,7,401,Grand Snow Palace,Suite,Shoulder Season 2026,450.0
8,4,202,Alpenblick Resort & Spa,Family Room,Winter Peak 2026,420.0
9,9,B20,Chalet Panorama Gstaad,Family Room,Winter Peak 2026,420.0


Short Interpretation

Returns only those room prices that are higher than the average seasonal room price\. The subquery calculates the average price\_per\_night from the view view\_room\_season\_price\. The outer query then returns all rooms where the price per night is above this average\.